name: Action
on:
  push:
    branches:
        - main
permissions:
  contents: write
env:
  filename: "my resume.pdf"

jobs:
  convert-file-and-release:
    runs-on: ubuntu-latest
    container:
      image: instructure/libreoffice:6.3
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Convert file
        id: convert
        run: |
          soffice --convert-to pdf "my resume.docx"

      - name: Delete Old Release
        uses: dev-drprasad/delete-older-releases@v0.2
        with:
          keep_latest: 0
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          tag_name: latest
          files: /__w/my-cv/my-cv/my resume.pdf