name: Action
on:
  push:

permissions:
  contents: write
env:
  filename: "my resume.pdf"

jobs:
  convert-file-and-release:
    runs-on: ubuntu-latest
    container:
      image: instructure/libreoffice:6.3
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Convert file
        id: convert
        run: |
          soffice --convert-to pdf "my resume.docx"
          mv "my resume.pdf" "mohamed-mohab-resume-${{ github.ref_name }}.pdf"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          tag_name: latest
          files: /__w/my-cv/my-cv/mohamed-mohab-resume-${{ github.ref_name }}.pdf